dataset:
  weekly: true

paths:
  sinan: data/processed/sinan/DENG240810.parquet
  cnes: data/processed/cnes/SRN2401.parquet
  era5: data/raw/era5/RJ_1997_2024.nc
  output: data/datasets/RN_WEEKLY_CASESONLY
  unidade: FULL

preproc:
  SLIDING_WINDOW_SIZE: 7
  MIN_DATE: 2016-01-01
  MAX_DATE: 2019-12-31
  TRAIN_SPLIT: 2018-01-01
  VAL_SPLIT: 2019-01-01

features:
  enable:
    cases_windows: false
    cases_accumulators: false
    cases_lags: false

    ideal_temp: false
    extreme_temp: false
    significant_rain: false
    extreme_rain: false
    temp_range: false
    week_of_year: false
    windows: false

    raw_features:
      tem_avg: false
      tem_min: true
      tem_max: true
      rain: true
      rh_avg: true
      rh_min: false
      rh_max: false

  windows: []  # como já é semanal, evita somar múltiplas semanas
  lags: 1

  temp:
    ideal_temp_range: [21, 27]
    extreme_temp_range: [14, 38]

  rain:
    significant_range: [0.010, 0.150]
    extreme_threshold: 0.150
