target: CASES
preproc:
  SLIDING_WINDOW_SIZE : 7
  TRAIN_SPLIT : '2012-12-31'
  VAL_SPLIT : '2022-12-31'
training:
  bc:
    BATCH_SIZE : 1024
    DROPOUT_RATE : 0.5
    LEARNING_RATE : 0.0003
    N_EPOCHS : 3500
    OUTPUT_SIZE : 1
    PATIENCE : 1000
    WEIGHT_DECAY : 0
  oc:
    BATCH_SIZE : 1024
    DROPOUT_RATE : 0.8
    LEARNING_RATE : 0.000003
    N_EPOCHS : 10000
    OUTPUT_SIZE : 5
    PATIENCE : 1000
    WEIGHT_DECAY : 0
  reg:
    BATCH_SIZE : 30
    DROPOUT_RATE : 0.5
    LEARNING_RATE : 0.0003
    N_EPOCHS : 1000
    OUTPUT_SIZE : 1
    PATIENCE : 500
    WEIGHT_DECAY : 0