name: atmoseer
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
    - python==3.12
    - pip
    - pip:
      - asttokens==2.0.5
      - backcall==0.2.0
      - boto3==1.34.137
      - certifi==2022.9.24
      - charset-normalizer==2.1.1
      - colorama==0.4.5
      - contourpy==1.0.5
      - cycler==0.11.0
      - debugpy==1.6.2
      - decorator==5.1.1
      - entrypoints==0.4
      - executing==0.9.1
      - fonttools==4.37.4
      - idna==3.4
      - ipykernel==6.15.1
      - ipython==8.4.0
      - jedi==0.18.1
      - joblib==1.2.0
      - jupyter-client==7.3.4
      - jupyter-core==4.11.1
      - kiwisolver==1.4.4
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.3
      - metpy==1.4.1
      - nest-asyncio==1.5.5
      - netcdf4==1.7.0
      - numpy==1.26
      - packaging==21.3
      - pandas==1.4.3
      - parso==0.8.3
      - pickleshare==0.7.5
      - pillow==9.2.0
      - prompt-toolkit==3.0.30
      - psutil==5.9.1
      - pure-eval==0.2.2
      - pygments==2.12.0
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2022.2.1
      - pyzmq==26.0.3
      - requests==2.28.1
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.12.0
      - six==1.16.0
      - sklearn==0.0
      - stack-data==0.3.0
      - threadpoolctl==3.1.0
      - torchvision==0.18.1
