DATASET: data/datasets/RN_DAILY/dataset.pickle
OUTDIR: models/eval_transfer_DAILY_FULL
MODEL_DIRS:
  - models/RJ_DAILY_FULL_987_rf
  - models/RJ_DAILY_FULL_987_xgb_poisson
  - models/RJ_DAILY_FULL_987_xgb_zip
