dataset: data/datasets/RJ_WEEKLY_CASESONLY/dataset.pickle
feature_dict: data/datasets/RJ_WEEKLY_CASESONLY/feature_dictionary.csv
output_dir: models/RJ_WEEKLY_CASESONLY
seed: 987

models:
  random_forest: true
  xgb_poisson: true
  xgb_zip: true
