dataset: data/datasets/RN_WEEKLY/dataset.pickle
feature_dict: data/datasets/RN_WEEKLY/feature_dictionary.csv
output_dir: models/RN_WEEKLY_FULL
seed: 987

models:
  random_forest: true
  xgb_poisson: true
  xgb_zip: true
