dataset: data/datasets/RN_DAILY_CASESONLY/RN_DAILY_CASESONLY.pickle
feature_dict: data/datasets/RN_DAILY_CASESONLY/feature_dictionary.csv
output_dir: models/RN_DAILY_CASEONLY
seed: 987

models:
  random_forest: true
  xgb_poisson: true
  xgb_zip: true
