dataset: data/datasets/RN_WEEKLY/dataset.pickle
feature_dict: data/datasets/RN_WEEKLY/feature_dictionary.csv
output_dir: results/RN_WEEKLY
seed: 42

models:
  random_forest: true
  xgb_poisson: true
  xgb_zip: true
