dataset: data/datasets/RJ_WEEKLY/dataset.pickle
feature_dict: data/datasets/RJ_WEEKLY/feature_dictionary.csv
output_dir: models/RJ_WEEKLY_FULL
seed: 987

models:
  random_forest: true
  xgb_poisson: true
  xgb_zip: true
