dataset: data/datasets/RN_DAILY/RN_DAILY.pickle
feature_dict: data/datasets/RN_DAILY/feature_dictionary.csv
output_dir: models/RN_DAILY_FULL
seed: 987

models:
  random_forest: true
  xgb_poisson: true
  xgb_zip: true
