dataset: data/datasets/RJ_DAILY_CASESONLY/dataset.pickle
feature_dict: data/datasets/RJ_DAILY_CASESONLY/feature_dictionary.csv
output_dir: models/RJ_DAILY_CASEONLY
seed: 987

models:
  random_forest: true
  xgb_poisson: true
  xgb_zip: true
